services:
  db:
    image: postgres:16.2-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: chleb
    ports:
      - 5432:5432
    volumes:
      - chleb_postgres_data:/var/lib/postgresql/data

volumes:
  chleb_postgres_data:
