name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  analyze_and_test:
    name: Analyze and Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Compile Main Code
        run: ./gradlew compileJava

      - name: Compile Test Code
        run: ./gradlew compileTestJava

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest

      - name: Run PMD
        run: ./gradlew pmdMain pmdTest

      - name: Run SpotBugs
        run: ./gradlew spotbugsMain spotbugsTest

      - name: Run tests
        run: ./gradlew test
